imports:
  - { resource: ./Shared/application.yaml }
  - { resource: ./apps/application.yaml }
  - { resource: ./User/application.yaml }
  #- { resource: ./Employees/application.yaml }
  #- { resource: ./Visit/application.yaml }