imports:
  - { resource: ./Shared/application.yaml }
  - { resource: ./apps/application.yaml }
  - { resource: ./User/application.yaml }
  - { resource: ./Tag/application.yaml }
  - { resource: ./Account/application.yaml }