services:
  Polvebra.shared.ConnectionManager:
    class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoConnectionManager
    arguments: []

  Polvebra.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Polvebra.shared.TokenRepository:
    class: ../../../../../Contexts/App/Shared/infrastructure/MongoTokenRepository
    arguments: []

  Polvebra.shared.LoginManager:
    class: ../../../../../Contexts/App/Shared/infrastructure/JWTLogin
    arguments: ['@Polvebra.shared.Logger, @Polvebra.shared.TokenRepository']

  Polvebra.shared.SessionManager:
    class: ../../../../../Contexts/App/Shared/infrastructure/SessionManagerJWT
    arguments: []

  Polvebra.shared.AuthenticationManager:
    class: ../../../../../Contexts/Shared/application/AuthenticationManager
    arguments: ['@Polvebra.shared.SessionManager']

  Polvebra.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemoryAsyncEventBus
    arguments: [ ]

  Polvebra.shared.EventBus.DomainEventMapping:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventMapping
    arguments: [ '!tagged domainEventSubscriber' ]

  Polvebra.shared.EventBus.DomainEventJsonDeserializer:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventJsonDeserializer
    arguments: [ '@Polvebra.shared.EventBus.DomainEventMapping' ]
